# Generated by Django 5.1.6 on 2025-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dietplan_surveyquestion_user_userdietplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='evening_snack',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='mid_morning_snack',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='preferences',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='diet_plan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='image_urls',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='max_age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='max_height',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='max_weight',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='min_height',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='min_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='UserDietPlan',
        ),
    ]
