# Generated by Django 5.1.6 on 2025-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_dietplan_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='max_calories',
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='min_calories',
            field=models.IntegerField(default=1500),
        ),
    ]
