# Generated by Django 5.1.6 on 2025-02-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dietplan_max_calories_dietplan_min_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='max_calories',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='min_calories',
        ),
    ]
