# Generated by Django 5.1.6 on 2025-09-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_dietplan_max_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
