# Generated by Django 5.1.6 on 2025-09-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
