# Generated by Django 5.2.7 on 2025-10-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_category_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
