# Generated by Django 5.2.7 on 2025-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workouts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
