# Generated by Django 5.2.7 on 2025-10-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_move',
            field=models.CharField(blank=True, default='BEST', max_length=25),
        ),
    ]
