# Generated by Django 5.2.7 on 2025-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_signature_move'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_mode',
            field=models.CharField(choices=[('habit', 'HabitForge'), ('emotion', 'MindSync')], default='habit', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_mood',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motivation_style',
            field=models.CharField(default='balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
    ]
