# Generated by Django 5.2.7 on 2025-10-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_options_userprofile_focus_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='focus_mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_mood',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='motivation_style',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='streak_days',
        ),
    ]
