# Generated by Django 5.2.7 on 2025-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_community_communitypost_membership_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('harassment', 'Harassment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
