# Generated by Django 5.1.6 on 2025-03-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='carbs_consumed',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fibres_consumed',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='proteins_consumed',
        ),
    ]
