# Generated by Django 5.1.6 on 2025-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_meal_carbs_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbs_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fibres_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins_consumed',
            field=models.FloatField(default=0.0),
        ),
    ]
