# Generated by Django 5.1.6 on 2025-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_bodysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysnapshot',
            name='body_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
