# Generated by Django 5.1.6 on 2025-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bodysnapshot_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysnapshot',
            name='hip_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodysnapshot',
            name='shoulder_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
