# Generated by Django 5.1.6 on 2025-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_unknownquestion_chatbotqa_delete_bodysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
