# Generated by Django 5.1.6 on 2025-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_unknownquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownquestion',
            name='answer1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unknownquestion',
            name='answer2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
