# Generated by Django 5.1.6 on 2025-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_foodprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprediction',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
